* Introduction

  Directory for testing FuzzChick.

* Installation

  Make sure you have the latest QuickChick submodule:

  #+BEGIN_SRC sh
    git pull
    git submodule update --init
  #+END_SRC

  In order to use FuzzChick you need the AFL instrumentation for ocaml:

  #+BEGIN_SRC sh
    opam switch create 4.04.0+afl
    opam install afl
    opam install afl-persistent
  #+END_SRC

  I believe this will set up an ocaml compiler which instruments
  binaries for AFL, and installs AFL via opam (not sure if the version
  from opam is special).

  You will need Coq, and some libraries for Coq as well.

  #+BEGIN_SRC sh
    opam repo add coq-released http://coq.inria.fr/opam/released
    opam install coq.8.8.2 && opam pin add coq 8.8.2

    opam install coq-ext-lib
    opam install coq-mathcomp-ssreflect
    opam install coq-simple-io
  #+END_SRC

  But that should be about it. After this FuzzChick should be
  relatively easy to install:

  #+BEGIN_SRC sh
    cd QuickChick
    make clean
    make
    make install
  #+END_SRC

* Running FuzzChick

  There is a [[./QuickChick/examples/fuzz-ifc][examples/fuzz-ifc]] directory in QuickChick that is related
  to FuzzChick. I am currently not too sure how to run this.

  There are some comments here:

  https://github.com/Quick700/Quick700/issues/5

  Sounds like FuzzChick will compile tests as a binary tester, which
  it then runs AFL on. The binary tester will intentionally crash when
  the checker fails for a given test.
