* Honggfuzz

** Git submodule

   This directory contains a few git submodules for Apache, it should
   be set to fetch version 2.4.37 of Apache's httpd, as well as the
   latest versions of ~apr~ and ~apr-util~.

   #+BEGIN_SRC sh
     git pull
     git submodule update --init
   #+END_SRC

   Should get you set up.

   #+BEGIN_SRC sh
     # Go into the apache directory
     cd apache

     # Apply the honggfuzz patch
     patch -p1 < ../hong-apache/httpd-master.honggfuzz.patch

     # Generate the configure script
     ./buildconf

     # Install using the modified honggfuzz configure script...
     # Make sure /usr/bin/env python launches python 2, otherwise this will fail.
     ./../compile_and_install_asan.sh
   #+END_SRC

   Now we just need to configure Apache's httpd for Honggfuzz... Unfortunately we have to edit some files.

   #+BEGIN_SRC sh
     # go back to Quick700/honggfuzz
     cd .. 
     ./make-configs.sh
   #+END_SRC

** Testing Apache

   [[https://github.com/google/honggfuzz/tree/master/examples/apache-httpd][Instructions for fuzzing apache 2.4 with Hongfuzz are here]]


*** Things to be aware of

    *You need to patch Apache's httpd as above*

*** TODO Fuzzing commands

    Should we fuzz both HTTP/1 and HTTP/2, or just one of those? I
    believe the DeepWeb server is starting with HTTP/2?

    *HTTP/1:*

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http1 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f httpd.conf.h1
    #+END_SRC

    *HTTP/2:*

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http2 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f httpd.conf.h2
    #+END_SRC

** Current Problems

   We seem to need to enable some more modules in Apache, which I have
   added to the ~./configure~ options above, but I still can't get it
   to run with the config files...

   Seems to need to run under root. I'm getting these issues, though:

   #+BEGIN_EXAMPLE
     $ sudo $HOME/fuzzpache/bin/httpd -DFOREGROUND -f $HOME/fuzzpache/conf/httpd.conf.h1

     [Wed Oct 24 11:31:54.451236 2018] [core:emerg] [pid 8080:tid 139831017579136] (22)Invalid argument: AH00024: Couldn't set permissions on the proxy mutex; check User and Group directives
     [Wed Oct 24 11:31:54.451279 2018] [proxy:crit] [pid 8080:tid 139831017579136] (22)Invalid argument: AH02478: failed to create proxy mutex
     AH00016: Configuration Failed
   #+END_EXAMPLE
