* Honggfuzz

** Git submodule

   This directory contains a few git submodules for Apache, it should
   be set to fetch version 2.4.37 of Apache's httpd, as well as the
   latest versions of ~apr~ and ~apr-util~.

   #+BEGIN_SRC sh
     git pull
     git submodule update --init
   #+END_SRC

   Should get you set up.

   #+BEGIN_SRC sh
     # Go into the apache directory
     cd apache

     # Apply the honggfuzz patch
     patch -p1 < ../hong-apache/httpd-master.honggfuzz.patch

     # Generate the configure script
     ./buildconf

     # Install using the modified honggfuzz configure script...
     # Make sure /usr/bin/env python launches python 2, otherwise this will fail.
     ./../compile_and_install_asan.sh
   #+END_SRC

   Now we just need to configure Apache's httpd for Honggfuzz... Unfortunately we have to edit some files.

   #+BEGIN_SRC sh
     # go back to Quick700/honggfuzz
     cd .. 
     ./make-configs.sh
   #+END_SRC

** Testing Apache

   [[https://github.com/google/honggfuzz/tree/master/examples/apache-httpd][Instructions for fuzzing apache 2.4 with Hongfuzz are here]]


*** Things to be aware of

    *You need to patch Apache's httpd as above*

*** TODO Fuzzing commands

    Should we fuzz both HTTP/1 and HTTP/2, or just one of those? I
    believe the DeepWeb server is starting with HTTP/2?

    *HTTP/1:*

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http1 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f httpd.conf.h1
    #+END_SRC

    *HTTP/2:*

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http2 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f httpd.conf.h2
    #+END_SRC

** Current Problems

   I think it might almost be working, but I get this when running Honggfuzz:

   #+BEGIN_EXAMPLE
     [2018-10-24T13:03:03-0400][W][5150] arch_checkWait():309 Persistent mode: PID 5152 exited with status: EXITED, exit code: 1
     Persistent mode: Launched new persistent PID: 5156
     [2018-10-24T13:03:03-0400][W][5149] arch_checkWait():309 Persistent mode: PID 5155 exited with status: EXITED, exit code: 1
     Persistent mode: Launched new persistent PID: 5159
     [2018-10-24T13:03:03-0400][W][5150] arch_checkWait():309 Persistent mode: PID 5156 exited with status: EXITED, exit code: 1
     Persistent mode: Launched new persistent PID: 5160
     [2018-10-24T13:03:03-0400][W][5149] arch_checkWait():309 Persistent mode: PID 5159 exited with status: EXITED, exit code: 1
     Persistent mode: Launched new persistent PID: 5163
     [2018-10-24T13:03:03-0400][W][5150] arch_checkWait():309 Persistent mode: PID 5160 exited with status: EXITED, exit code: 1
     Persistent mode: Launched new persistent PID: 5164
     [2018-10-24T13:03:03-0400][W][5149] arch_checkWait():309 Persistent mode: PID 5163 exited with status: EXITED, exit code: 1
     Persistent mode: Launched new persistent PID: 5167
   #+END_EXAMPLE

   When trying to start the server on its own I get:

   #+BEGIN_EXAMPLE
     $ ./dist/bin/httpd -DFOREGROUND -f httpd.conf.h1

     Honggfuzz Net Driver (pid=5381): TCP port:8080 will be used
     [2018-10-24T13:03:16-0400][W][5381] netDriver_sockConn():173 Honggfuzz Net Driver (pid=5381): couldn't connect(loopback, port:8080)
     Honggfuzz Net Driver (pid=5381): Waiting for the TCP server process to start accepting TCP connections at 127.0.0.1:8080. Sleeping for 1 second....
     httpd: Could not open configuration file /home/calvin/git/Quick700/honggfuzz/dist/httpd.conf.h1: No such file or directory
   #+END_EXAMPLE

   Not sure if running Honggfuzz as above will make it connect and not
   immediately die like this. Maybe that connection is messed up.
