* Honggfuzz

** Use Docker

   #+BEGIN_SRC sh :shebang "#!/bin/sh"
     docker run -it --privileged ysli/fuzz-apache:hong
   #+END_SRC

   Once you launched the container, test with:

   #+BEGIN_SRC sh
     ./fuzz-h1.sh
   #+END_SRC

   or

   #+BEGIN_SRC sh
     ./fuzz-h2.sh
   #+END_SRC

** Git submodule

   This directory contains a few git submodules for Apache, it should
   be set to fetch version 2.4.37 of Apache's httpd, as well as the
   latest versions of ~apr~ and ~apr-util~.

   All of these commands are extracted from org-babel into the
   ~setup-honggfuzz.sh~ file, which you should be able to execute in
   order to setup Honggfuzz.

   #+BEGIN_SRC sh
     git pull
     git submodule update --init
   #+END_SRC

   Should get you set up.
   
   Before attempting the below you may need to compile Honggfuzz
   
   #+BEGIN_SRC sh  :tangle setup-honggfuzz.sh :shebang "#!/bin/sh"
     cd honggfuzz
     make
     cd ..
   #+END_SRC

   # On the OpenSuse machines I had to do:

   # #+BEGIN_SRC sh
   #   LD_LIBRARY_PATH=$HOME:$LD_LIBRARY_PATH LDFLAGS="-L$HOME -lbfd -lopcodes -lz $HOME/libiberty.a" make
   # #+END_SRC

   with the appropriate libraries copied over.

   #+BEGIN_SRC sh :tangle setup-honggfuzz.sh
     # Go into the apache directory
     cd apache

     # Apply the honggfuzz patch
     patch -p1 < ../hong-apache/httpd-master.honggfuzz.patch

     # Generate the configure script
     ./buildconf

     # Install using the modified honggfuzz configure script...
     # Make sure /usr/bin/env python launches python 2, otherwise this will fail.
     ./../compile_and_install.asan.sh
   #+END_SRC

   Now we just need to configure Apache's httpd for Honggfuzz... Unfortunately we have to edit some files.

   #+BEGIN_SRC sh :tangle setup-honggfuzz.sh
     # go back to Quick700/honggfuzz
     cd .. 
     ./make-configs.sh
   #+END_SRC

** Testing Apache

   [[https://github.com/google/honggfuzz/tree/master/examples/apache-httpd][Instructions for fuzzing apache 2.4 with Hongfuzz are here]]


*** Things to be aware of

    *You need to patch Apache's httpd as above*

*** TODO Fuzzing commands

    Should we fuzz both HTTP/1 and HTTP/2, or just one of those? I
    believe the DeepWeb server is starting with HTTP/2?

    *HTTP/1:*

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http1 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f $PWD/httpd.conf.h1
    #+END_SRC

    *HTTP/2:*

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http2 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f $PWD/httpd.conf.h2
    #+END_SRC

** Known Problems

*** Not running httpd with a full path to the config file
    
    I got this issue when running Honggfuzz at first.

    #+BEGIN_EXAMPLE
      [2018-10-24T13:03:03-0400][W][5150] arch_checkWait():309 Persistent mode: PID 5152 exited with status: EXITED, exit code: 1
      Persistent mode: Launched new persistent PID: 5156
      [2018-10-24T13:03:03-0400][W][5149] arch_checkWait():309 Persistent mode: PID 5155 exited with status: EXITED, exit code: 1
      Persistent mode: Launched new persistent PID: 5159
      [2018-10-24T13:03:03-0400][W][5150] arch_checkWait():309 Persistent mode: PID 5156 exited with status: EXITED, exit code: 1
      Persistent mode: Launched new persistent PID: 5160
      [2018-10-24T13:03:03-0400][W][5149] arch_checkWait():309 Persistent mode: PID 5159 exited with status: EXITED, exit code: 1
      Persistent mode: Launched new persistent PID: 5163
      [2018-10-24T13:03:03-0400][W][5150] arch_checkWait():309 Persistent mode: PID 5160 exited with status: EXITED, exit code: 1
      Persistent mode: Launched new persistent PID: 5164
      [2018-10-24T13:03:03-0400][W][5149] arch_checkWait():309 Persistent mode: PID 5163 exited with status: EXITED, exit code: 1
      Persistent mode: Launched new persistent PID: 5167
    #+END_EXAMPLE

    Turns out that this was due to not providing the full path to ~httpd~:

    #+BEGIN_SRC sh
      honggfuzz -f hong-apache/corpus_http2 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f httpd.conf.h2
    #+END_SRC
